# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hello and welcome to the Oni repository! Thanks for opening your first issue here. To help us out, please make sure to include as much detail as possible - including screenshots and logs, if possible.
nonBackerComment: >
  Thanks for using Oni and creating this issue!
backers:
- 1
- 2
- 13532591
